//! The constructed test vectors (test-vectors/constructed.json): one Orchard and one Ironwood transaction,
//! each paying a merchant and a second party from a transparent coin, built from label-derived keys. The
//! file is exactly what `vectors()` builds; the other tests read it.
//!
//! Regenerate with: `cargo test --release --test vectors -- --ignored generate`

mod common;

use common::{address, ufvk, uivk, Payment};
use serde_json::{json, Value};
use zcash_delivery_proof::{check, make, memo_text, receiver_address, DeliveryProof, Pool, Side, ViewingKeys};
use zcash_protocol::consensus::NetworkType;

const CASES: [(&str, Pool); 2] = [("orchard", Pool::Orchard), ("ironwood", Pool::Ironwood)];

fn payments(case: &str) -> [Payment; 2] {
    let (merchant, other) = match case {
        "orchard" => ("vectors/orchard/merchant", "vectors/orchard/other"),
        _ => ("vectors/ironwood/merchant", "vectors/ironwood/other"),
    };
    [
        Payment { to: merchant, value: 123_456, memo: "Invoice 1042: 0.00123456 ZEC for two bags of coffee beans" },
        Payment { to: other, value: 40_000, memo: "a second payment in the same transaction" },
    ]
}

fn vectors() -> Value {
    let cases: Vec<Value> = CASES
        .iter()
        .map(|(case, pool)| {
            let name = format!("vectors/{case}");
            let sender = format!("vectors/{case}/sender");
            let ps = payments(case);
            let tx = common::build(*pool, &name, &sender, &ps);
            let sent = make(&tx, &ViewingKeys::parse(&ufvk(&sender)).unwrap()).unwrap();
            assert_eq!(sent.len(), 2, "the sender sees both payments");
            let t = zcash_delivery_proof::read_tx(&tx).unwrap();
            let mut txid = *t.txid().as_ref();
            txid.reverse();
            json!({
                "name": case,
                "pool": pool,
                "network": "testnet",
                "txid": hex::encode(txid),
                "txHex": hex::encode(&tx),
                "spent": [{ "value": common::COIN_VALUE, "scriptPubKey": hex::encode(common::coin_script(&name)) }],
                "keys": {
                    "merchantUfvk": ufvk(ps[0].to),
                    "merchantUivk": uivk(ps[0].to),
                    "otherUfvk": ufvk(ps[1].to),
                    "senderUfvk": ufvk(&sender),
                    "strangerUfvk": ufvk("vectors/stranger"),
                },
                "payments": ps.iter().map(|p| {
                    let f = sent.iter().find(|f| f.proof.receiver == address(p.to).to_raw_address_bytes()).expect("each payment is found");
                    json!({
                        "to": receiver_address(&f.proof.receiver, NetworkType::Test),
                        "value": p.value,
                        "memoText": p.memo,
                        "action": f.proof.action,
                        "proof": f.proof.encode(),
                    })
                }).collect::<Vec<_>>(),
            })
        })
        .collect();
    json!({ "_comment": "Delivery proofs of payments built by librustzcash from keys derived from labels under \"sapling.cash/zdp/\" (tests/common; testnet rules, never broadcast). Generated by tests/vectors.rs.", "cases": cases })
}

const FILE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/test-vectors/constructed.json");

fn file() -> Value {
    serde_json::from_str(&std::fs::read_to_string(FILE).expect("test-vectors/constructed.json")).unwrap()
}

#[test]
fn the_vectors_file_matches() {
    assert_eq!(file(), vectors());
}

#[test]
#[ignore]
fn generate() {
    std::fs::write(FILE, serde_json::to_string_pretty(&vectors()).unwrap() + "\n").unwrap();
}

fn tx_of(case: &Value) -> Vec<u8> {
    hex::decode(case["txHex"].as_str().unwrap()).unwrap()
}

fn found(case: &Value, key: &str) -> Vec<zcash_delivery_proof::Found> {
    make(&tx_of(case), &ViewingKeys::parse(case["keys"][key].as_str().unwrap()).unwrap()).unwrap()
}

#[test]
fn each_key_sees_exactly_its_notes() {
    for case in file()["cases"].as_array().unwrap() {
        let proofs: Vec<&str> = case["payments"].as_array().unwrap().iter().map(|p| p["proof"].as_str().unwrap()).collect();
        // the merchant, with its full or its incoming viewing key: its payment, received
        for key in ["merchantUfvk", "merchantUivk"] {
            let f = found(case, key);
            assert_eq!(f.len(), 1, "{key}");
            assert_eq!((f[0].side, f[0].proof.encode().as_str()), (Side::Received, proofs[0]), "{key}");
        }
        // the other recipient: its own payment only
        let f = found(case, "otherUfvk");
        assert_eq!((f.len(), f[0].proof.encode().as_str()), (1, proofs[1]));
        // the sender, through its outgoing viewing key: both, sent, with the same proofs
        let f = found(case, "senderUfvk");
        let got: Vec<(Side, String)> = f.iter().map(|x| (x.side, x.proof.encode())).collect();
        assert_eq!(got.len(), 2);
        for p in &proofs {
            assert!(got.contains(&(Side::Sent, p.to_string())), "the sender sees {p}");
        }
        // a stranger: nothing
        assert!(found(case, "strangerUfvk").is_empty());
    }
}

#[test]
fn every_proof_checks_with_no_key() {
    for case in file()["cases"].as_array().unwrap() {
        let tx = tx_of(case);
        for p in case["payments"].as_array().unwrap() {
            let proof = DeliveryProof::decode(p["proof"].as_str().unwrap()).unwrap();
            let d = check(&tx, &proof).unwrap();
            assert_eq!(d.txid_hex(), case["txid"].as_str().unwrap());
            assert_eq!(serde_json::to_value(d.pool).unwrap(), case["pool"]);
            assert_eq!(d.value, p["value"].as_u64().unwrap());
            assert_eq!(memo_text(&d.memo).as_deref(), p["memoText"].as_str());
            assert_eq!(receiver_address(&d.receiver, NetworkType::Test), p["to"].as_str().unwrap());
            assert_eq!(d.view(NetworkType::Test).address, p["to"].as_str().unwrap());
            // the proof's text and bytes round trip
            assert_eq!(DeliveryProof::from_bytes(&proof.to_bytes()).unwrap(), proof);
        }
    }
}

#[test]
fn a_proof_names_the_receiver_inside_a_fuller_address() {
    use zcash_address::unified::{self, Encoding};
    let case = &file()["cases"][0];
    let proof = DeliveryProof::decode(case["payments"][0]["proof"].as_str().unwrap()).unwrap();
    // the merchant's published address carries a transparent receiver too; the proof names its Orchard part
    let full = unified::Address::try_from_items(vec![unified::Receiver::P2pkh(common::label("vectors/merchant-p2pkh")), unified::Receiver::Orchard(proof.receiver)]).unwrap().encode(&NetworkType::Test);
    assert!(zcash_delivery_proof::address_has_receiver(&full, &proof.receiver));
    assert!(!zcash_delivery_proof::address_has_receiver(&full, &address("vectors/stranger").to_raw_address_bytes()));
}
